# Generated by Django 3.0.7 on 2020-10-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endApi', '0045_auto_20200926_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_on']},
        ),
    ]
